### ISSUE TITLE
Roadmap for 0.1

### ISSUE THREAD

**Issue by martinfleis** [geopandas/xyzservices#1]
- [x] move static contextily providers to xyzservices
- [x] switch to JSON and on-the-fly creation of `Bunch`
- [ ] ~~allow to load more providers via a function (#12)~~
- [ ] ~~allow to load remote JSONs (#14)~~
- [ ] ~~allow to load more JSONs into a single Bunch (#14)~~
- [x] method to retrieve URL (#13)
- [x] docs (#15)
- [x] CI
- [x] tests (#16)
- [x] develop the protocol for expansion of the source JSON (#10 )

**Comment by darribas** [comment]
Adding new providers and loading JSON files is left for the future, everything else is in already.
